# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
