# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
