# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20171026_1510'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('detail_type', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='t_department',
            name='company_id',
        ),
        migrations.DeleteModel(
            name='t_Department',
        ),
    ]
