# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20171013_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Companies'},
        ),
    ]
