# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zipcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=140)),
                ('landmark', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zipcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zipcodes.Zipcode')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
